include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    close_sinks: ignore
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/generated/**'
    - 'lib/models/**'